services:
  - type: web
    name: portfolio-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        value: abhiabhiramreddy32@gmail.com
      - key: EMAIL_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
